Arbitrary ORTB request configuration changes
prebid/prebid-mobile-ios pull request #1064
Opened 2024-11-22 09:35 UTC by OlenaPostindustria

#1017

2024-12-02 09:33 UTC, OlenaPostindustria commented on PrebidMobile/PrebidMobileRendering/Networking/Parameters/ArbitraryORTBHelper.swift
> +        static var deviceProps: [String] {
Yes, it seems like a more memory-efficient solution.

2024-12-02 09:37 UTC, OlenaPostindustria commented on PrebidMobileTests/RenderingTests/Tests/ParameterBuilderTests/ArbitraryORTBHelperTests.swift
> +    func testGlobalORTBHelper_ValidJSON_RemoveProtectedFields() {
Already added some tests in [ArbitraryORTBServiceTests](https://github.com/prebid/prebid-mobile-ios/blob/d194a009a3705e3017fedcfbd9a81f7c8224447a/PrebidMobileTests/RenderingTests/Tests/ParameterBuilderTests/ArbitraryORTBServiceTests.swift).

2024-12-03 11:43 UTC, YuriyVelichkoPI approved these changes
LGTM

2024-12-04 10:19 UTC, YuriyVelichkoPI requested changes

2024-12-04 10:19 UTC, YuriyVelichkoPI commented on PrebidMobile/ConfigurationAndTargeting/Targeting.swift
> +    public func setGlobalORTBConfig(_ ortbConfig: String?) {
Please add an example of how this method is used in the demo apps. 

Let's set: 
- `ext.myext.test = 1` 
- `displaymanager` = Google
- `displaymanagerver` = $CurrentGMASDKVersion

2024-12-04 10:19 UTC, YuriyVelichkoPI commented on PrebidMobile/AdUnits/MultiformatAdUnit/PrebidRequest.swift
> +    public func setImpressionORTBConfig(_ ortbConfig: String?) {
Please add an example of how this method is used in the demo apps. 

Let's set: 
- `imp.bidfloor=10` 
- `imp.banner.battr` = [1,2,3,4]

2024-12-06 08:15 UTC, YuriyVelichkoPI requested changes

2024-12-06 08:15 UTC, YuriyVelichkoPI commented on PrebidMobile/AdUnits/AdUnit.swift
> +    public func setImpressionORTBConfig(_ ortbConfig: String?) {
Please, rename to `setImpORTBConfig`

2024-12-19 07:53 UTC, YuriyVelichkoPI approved these changes

2024-12-19 07:53 UTC, merged