[CODE UNIFICATION] Introduce protocols for Ad Unit Configuration
prebid/prebid-mobile-ios pull request #550
Opened 2022-03-02 15:43 UTC by OlenaPostindustria

2022-03-04 14:48 UTC, ValentinPostindustria approved these changes
LGTM

2022-03-07 11:45 UTC, YuriyVelichkoPI requested changes

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on Example/PrebidDemo/PrebidDemoTests/PrebidDemoTests.swift
> +                prebidbBannerAdUnit.adUnitConfig.adSize = CGSize(width: 728, height: 90)
we should keep the original API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on InternalTestApp/PrebidMobileDemoRendering/ViewControllers/Adapters/Prebid/GAM/PrebidGAMNativeAdController.swift
> +        adUnit = NativeRequest(configId: prebidConfigId)
we should keep API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on InternalTestApp/PrebidMobileDemoRendering/ViewControllers/Adapters/Prebid/OpenX/PrebidNativeAdController.swift
> +        adUnit = NativeRequest(configId: configId)
we should keep API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on InternalTestApp/PrebidMobileDemoRendering/ViewControllers/Adapters/Prebid/OpenX/PrebidNativeAdController.swift
> +        adUnit = NativeRequest(configId: configId)
we should keep API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on InternalTestApp/PrebidMobileDemoRendering/ViewControllers/Adapters/Prebid/OpenX/PrebidNativeAdFeedController.swift
> +        adUnit = NativeRequest(configId: configId)
we should keep API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on InternalTestApp/PrebidMobileDemoRendering/ViewControllers/TableCells/FeedGAMAdTableViewCell.swift
> +        adUnit = NativeRequest(configId: configId)
we should keep API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on PrebidMobile/AdUnits/AdUnit.swift
> -        if !(self is NativeRequest){
Are you sure that we can remove this code?

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on PrebidMobileTests/AdUnitTests/AdUnitSuccessorObjCTests.m
> +    BaseAdUnit *adunit = [[VideoAdUnit alloc] initWithConfigId:configId size:CGSizeMake(300, 250)];
Why we can't use AdUnit anymore?

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on PrebidMobileTests/AdUnitTests/AdUnitSuccessorTests.swift
> +        adUnit.adUnitConfig.adSize = CGSize(width: Constants.width2, height: Constants.height2)
we should keep API here

2022-03-07 11:45 UTC, YuriyVelichkoPI commented on PrebidMobileTests/AdUnitTests/AdUnitTests.swift
> -        let adUnit = AdUnit(configId: "138c4d03-0efb-4498-9dc6-cb5a9acb2ea4", size: CGSize(width: 300, height: 250))
Need to be sure that we still have the original construction method. I saw that it was removed above.

2022-03-07 15:30 UTC, YuriyVelichkoPI approved these changes
LGTM

2022-03-07 15:30 UTC, merged