[CODE UNIFICATION] Use the PrebidRenderingTargeting class instead of OriginalTargetingProtocol
prebid/prebid-mobile-ios pull request #557
Opened 2022-03-11 11:43 UTC by OlenaPostindustria

Closes #539, #543

2022-03-11 13:02 UTC, ValentinPostindustria approved these changes
LGTM

2022-03-13 09:42 UTC, YuriyVelichkoPI requested changes

2022-03-13 09:42 UTC, YuriyVelichkoPI commented on InternalTestApp/PrebidMobileDemoRendering/Model/TestCasesManager.swift
> +            targeting.gender = TestCaseManager.strToGender(value)
Need to rename this property back to `userGender`

2022-03-14 09:31 UTC, YuriyVelichkoPI approved these changes
LGTM

2022-03-14 09:31 UTC, merged